export const dataApi = 
[
  {
  url: "https://api.github.com/repos/tidyverse/ggplot2/issues/4004",
  repository_url: "https://api.github.com/repos/tidyverse/ggplot2",
  labels_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/4004/labels{/name}",
  comments_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/4004/comments",
  events_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/4004/events",
  html_url: "https://github.com/tidyverse/ggplot2/issues/4004",
  id: 619152571,
  node_id: "MDU6SXNzdWU2MTkxNTI1NzE=",
  number: 4004,
  title: "Bin breaks are chosen awkwardly for stat_density_2d",
  user: {
  login: "tjebo",
  id: 36016789,
  node_id: "MDQ6VXNlcjM2MDE2Nzg5",
  avatar_url: "https://avatars1.githubusercontent.com/u/36016789?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/tjebo",
  html_url: "https://github.com/tjebo",
  followers_url: "https://api.github.com/users/tjebo/followers",
  following_url: "https://api.github.com/users/tjebo/following{/other_user}",
  gists_url: "https://api.github.com/users/tjebo/gists{/gist_id}",
  starred_url: "https://api.github.com/users/tjebo/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/tjebo/subscriptions",
  organizations_url: "https://api.github.com/users/tjebo/orgs",
  repos_url: "https://api.github.com/users/tjebo/repos",
  events_url: "https://api.github.com/users/tjebo/events{/privacy}",
  received_events_url: "https://api.github.com/users/tjebo/received_events",
  type: "User",
  site_admin: false
  },
  labels: [ ],
  state: "open",
  locked: false,
  assignee: null,
  assignees: [ ],
  milestone: {
  url: "https://api.github.com/repos/tidyverse/ggplot2/milestones/21",
  html_url: "https://github.com/tidyverse/ggplot2/milestone/21",
  labels_url: "https://api.github.com/repos/tidyverse/ggplot2/milestones/21/labels",
  id: 5181145,
  node_id: "MDk6TWlsZXN0b25lNTE4MTE0NQ==",
  number: 21,
  title: "ggplot2 3.3.1",
  description: "This will be a small patch release fixing regressions, improving performance, and folding in TDD PRs",
  creator: {
  login: "thomasp85",
  id: 1775316,
  node_id: "MDQ6VXNlcjE3NzUzMTY=",
  avatar_url: "https://avatars3.githubusercontent.com/u/1775316?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/thomasp85",
  html_url: "https://github.com/thomasp85",
  followers_url: "https://api.github.com/users/thomasp85/followers",
  following_url: "https://api.github.com/users/thomasp85/following{/other_user}",
  gists_url: "https://api.github.com/users/thomasp85/gists{/gist_id}",
  starred_url: "https://api.github.com/users/thomasp85/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/thomasp85/subscriptions",
  organizations_url: "https://api.github.com/users/thomasp85/orgs",
  repos_url: "https://api.github.com/users/thomasp85/repos",
  events_url: "https://api.github.com/users/thomasp85/events{/privacy}",
  received_events_url: "https://api.github.com/users/thomasp85/received_events",
  type: "User",
  site_admin: false
  },
  open_issues: 10,
  closed_issues: 34,
  state: "open",
  created_at: "2020-03-09T08:30:16Z",
  updated_at: "2020-05-16T17:04:24Z",
  due_on: null,
  closed_at: null
  },
  comments: 1,
  created_at: "2020-05-15T18:12:20Z",
  updated_at: "2020-05-15T18:23:10Z",
  closed_at: null,
  author_association: "NONE",
  body: "This is a follow up from #4003 "
  },
  {
  url: "https://api.github.com/repos/tidyverse/ggplot2/issues/4002",
  repository_url: "https://api.github.com/repos/tidyverse/ggplot2",
  labels_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/4002/labels{/name}",
  comments_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/4002/comments",
  events_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/4002/events",
  html_url: "https://github.com/tidyverse/ggplot2/pull/4002",
  id: 618948558,
  node_id: "MDExOlB1bGxSZXF1ZXN0NDE4NTc3Mzg5",
  number: 4002,
  title: "Allow using optional_aes in Stat",
  user: {
  login: "thomasp85",
  id: 1775316,
  node_id: "MDQ6VXNlcjE3NzUzMTY=",
  avatar_url: "https://avatars3.githubusercontent.com/u/1775316?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/thomasp85",
  html_url: "https://github.com/thomasp85",
  followers_url: "https://api.github.com/users/thomasp85/followers",
  following_url: "https://api.github.com/users/thomasp85/following{/other_user}",
  gists_url: "https://api.github.com/users/thomasp85/gists{/gist_id}",
  starred_url: "https://api.github.com/users/thomasp85/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/thomasp85/subscriptions",
  organizations_url: "https://api.github.com/users/thomasp85/orgs",
  repos_url: "https://api.github.com/users/thomasp85/repos",
  events_url: "https://api.github.com/users/thomasp85/events{/privacy}",
  received_events_url: "https://api.github.com/users/thomasp85/received_events",
  type: "User",
  site_admin: false
  },
  labels: [ ],
  state: "open",
  locked: false,
  assignee: null,
  assignees: [ ],
  milestone: {
  url: "https://api.github.com/repos/tidyverse/ggplot2/milestones/21",
  html_url: "https://github.com/tidyverse/ggplot2/milestone/21",
  labels_url: "https://api.github.com/repos/tidyverse/ggplot2/milestones/21/labels",
  id: 5181145,
  node_id: "MDk6TWlsZXN0b25lNTE4MTE0NQ==",
  number: 21,
  title: "ggplot2 3.3.1",
  description: "This will be a small patch release fixing regressions, improving performance, and folding in TDD PRs",
  creator: {
  login: "thomasp85",
  id: 1775316,
  node_id: "MDQ6VXNlcjE3NzUzMTY=",
  avatar_url: "https://avatars3.githubusercontent.com/u/1775316?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/thomasp85",
  html_url: "https://github.com/thomasp85",
  followers_url: "https://api.github.com/users/thomasp85/followers",
  following_url: "https://api.github.com/users/thomasp85/following{/other_user}",
  gists_url: "https://api.github.com/users/thomasp85/gists{/gist_id}",
  starred_url: "https://api.github.com/users/thomasp85/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/thomasp85/subscriptions",
  organizations_url: "https://api.github.com/users/thomasp85/orgs",
  repos_url: "https://api.github.com/users/thomasp85/repos",
  events_url: "https://api.github.com/users/thomasp85/events{/privacy}",
  received_events_url: "https://api.github.com/users/thomasp85/received_events",
  type: "User",
  site_admin: false
  },
  open_issues: 10,
  closed_issues: 34,
  state: "open",
  created_at: "2020-03-09T08:30:16Z",
  updated_at: "2020-05-16T17:04:24Z",
  due_on: null,
  closed_at: null
  },
  comments: 0,
  created_at: "2020-05-15T12:57:21Z",
  updated_at: "2020-05-15T23:55:32Z",
  closed_at: null,
  author_association: "MEMBER",
  pull_request: {
  url: "https://api.github.com/repos/tidyverse/ggplot2/pulls/4002",
  html_url: "https://github.com/tidyverse/ggplot2/pull/4002",
  diff_url: "https://github.com/tidyverse/ggplot2/pull/4002.diff",
  patch_url: "https://github.com/tidyverse/ggplot2/pull/4002.patch"
  },
  body: "This comes out of the discussion in #3860 which surfaced that Stat did not have the same `optional_aes` field as Geom. This PR simply mirrors the Geom implementation so that Stats can declare optional aesthetics. I'd like to get this into 3.3.1 so I can use it in the book"
  },
  {
  url: "https://api.github.com/repos/tidyverse/ggplot2/issues/4000",
  repository_url: "https://api.github.com/repos/tidyverse/ggplot2",
  labels_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/4000/labels{/name}",
  comments_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/4000/comments",
  events_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/4000/events",
  html_url: "https://github.com/tidyverse/ggplot2/issues/4000",
  id: 618850919,
  node_id: "MDU6SXNzdWU2MTg4NTA5MTk=",
  number: 4000,
  title: "using weights with stat_summary()",
  user: {
  login: "larmarange",
  id: 966307,
  node_id: "MDQ6VXNlcjk2NjMwNw==",
  avatar_url: "https://avatars1.githubusercontent.com/u/966307?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/larmarange",
  html_url: "https://github.com/larmarange",
  followers_url: "https://api.github.com/users/larmarange/followers",
  following_url: "https://api.github.com/users/larmarange/following{/other_user}",
  gists_url: "https://api.github.com/users/larmarange/gists{/gist_id}",
  starred_url: "https://api.github.com/users/larmarange/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/larmarange/subscriptions",
  organizations_url: "https://api.github.com/users/larmarange/orgs",
  repos_url: "https://api.github.com/users/larmarange/repos",
  events_url: "https://api.github.com/users/larmarange/events{/privacy}",
  received_events_url: "https://api.github.com/users/larmarange/received_events",
  type: "User",
  site_admin: false
  },
  labels: [ ],
  state: "open",
  locked: false,
  assignee: null,
  assignees: [ ],
  milestone: null,
  comments: 0,
  created_at: "2020-05-15T10:02:59Z",
  updated_at: "2020-05-15T10:02:59Z",
  closed_at: null,
  author_association: "NONE",
  body: "Currently, a variable mapped to `weight` aesthetic is not taken into account by `stat_summary()`. In such a situation, maybe a warning should be displayed as some users will expect that these weights will be taken into account in the computation. In addition, considering a version of `stat_summary()` able to deal with weights could be relevant. Regards"
  },
  {
  url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3999",
  repository_url: "https://api.github.com/repos/tidyverse/ggplot2",
  labels_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3999/labels{/name}",
  comments_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3999/comments",
  events_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3999/events",
  html_url: "https://github.com/tidyverse/ggplot2/pull/3999",
  id: 618836547,
  node_id: "MDExOlB1bGxSZXF1ZXN0NDE4NDg1MDU1",
  number: 3999,
  title: "remove NA breaks before creating the guides",
  user: {
  login: "thomasp85",
  id: 1775316,
  node_id: "MDQ6VXNlcjE3NzUzMTY=",
  avatar_url: "https://avatars3.githubusercontent.com/u/1775316?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/thomasp85",
  html_url: "https://github.com/thomasp85",
  followers_url: "https://api.github.com/users/thomasp85/followers",
  following_url: "https://api.github.com/users/thomasp85/following{/other_user}",
  gists_url: "https://api.github.com/users/thomasp85/gists{/gist_id}",
  starred_url: "https://api.github.com/users/thomasp85/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/thomasp85/subscriptions",
  organizations_url: "https://api.github.com/users/thomasp85/orgs",
  repos_url: "https://api.github.com/users/thomasp85/repos",
  events_url: "https://api.github.com/users/thomasp85/events{/privacy}",
  received_events_url: "https://api.github.com/users/thomasp85/received_events",
  type: "User",
  site_admin: false
  },
  labels: [ ],
  state: "open",
  locked: false,
  assignee: null,
  assignees: [ ],
  milestone: {
  url: "https://api.github.com/repos/tidyverse/ggplot2/milestones/21",
  html_url: "https://github.com/tidyverse/ggplot2/milestone/21",
  labels_url: "https://api.github.com/repos/tidyverse/ggplot2/milestones/21/labels",
  id: 5181145,
  node_id: "MDk6TWlsZXN0b25lNTE4MTE0NQ==",
  number: 21,
  title: "ggplot2 3.3.1",
  description: "This will be a small patch release fixing regressions, improving performance, and folding in TDD PRs",
  creator: {
  login: "thomasp85",
  id: 1775316,
  node_id: "MDQ6VXNlcjE3NzUzMTY=",
  avatar_url: "https://avatars3.githubusercontent.com/u/1775316?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/thomasp85",
  html_url: "https://github.com/thomasp85",
  followers_url: "https://api.github.com/users/thomasp85/followers",
  following_url: "https://api.github.com/users/thomasp85/following{/other_user}",
  gists_url: "https://api.github.com/users/thomasp85/gists{/gist_id}",
  starred_url: "https://api.github.com/users/thomasp85/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/thomasp85/subscriptions",
  organizations_url: "https://api.github.com/users/thomasp85/orgs",
  repos_url: "https://api.github.com/users/thomasp85/repos",
  events_url: "https://api.github.com/users/thomasp85/events{/privacy}",
  received_events_url: "https://api.github.com/users/thomasp85/received_events",
  type: "User",
  site_admin: false
  },
  open_issues: 10,
  closed_issues: 34,
  state: "open",
  created_at: "2020-03-09T08:30:16Z",
  updated_at: "2020-05-16T17:04:24Z",
  due_on: null,
  closed_at: null
  },
  comments: 0,
  created_at: "2020-05-15T09:38:43Z",
  updated_at: "2020-05-15T09:38:43Z",
  closed_at: null,
  author_association: "MEMBER",
  pull_request: {
  url: "https://api.github.com/repos/tidyverse/ggplot2/pulls/3999",
  html_url: "https://github.com/tidyverse/ggplot2/pull/3999",
  diff_url: "https://github.com/tidyverse/ggplot2/pull/3999.diff",
  patch_url: "https://github.com/tidyverse/ggplot2/pull/3999.patch"
  },
  body: "Fix #3876 This PR makes sure NA are not represented in the guide. Whether these guides (and colourbar) should actually represent `NA` (in a more aesthetically pleasing way) is a discussion for later when a guide rewrite is done"
  },
  {
  url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3997",
  repository_url: "https://api.github.com/repos/tidyverse/ggplot2",
  labels_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3997/labels{/name}",
  comments_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3997/comments",
  events_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3997/events",
  html_url: "https://github.com/tidyverse/ggplot2/issues/3997",
  id: 618772514,
  node_id: "MDU6SXNzdWU2MTg3NzI1MTQ=",
  number: 3997,
  title: "Integrating new grid features in ggplot2",
  user: {
  login: "thomasp85",
  id: 1775316,
  node_id: "MDQ6VXNlcjE3NzUzMTY=",
  avatar_url: "https://avatars3.githubusercontent.com/u/1775316?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/thomasp85",
  html_url: "https://github.com/thomasp85",
  followers_url: "https://api.github.com/users/thomasp85/followers",
  following_url: "https://api.github.com/users/thomasp85/following{/other_user}",
  gists_url: "https://api.github.com/users/thomasp85/gists{/gist_id}",
  starred_url: "https://api.github.com/users/thomasp85/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/thomasp85/subscriptions",
  organizations_url: "https://api.github.com/users/thomasp85/orgs",
  repos_url: "https://api.github.com/users/thomasp85/repos",
  events_url: "https://api.github.com/users/thomasp85/events{/privacy}",
  received_events_url: "https://api.github.com/users/thomasp85/received_events",
  type: "User",
  site_admin: false
  },
  labels: [ ],
  state: "open",
  locked: false,
  assignee: null,
  assignees: [ ],
  milestone: null,
  comments: 2,
  created_at: "2020-05-15T07:52:23Z",
  updated_at: "2020-05-15T22:12:20Z",
  closed_at: null,
  author_association: "MEMBER",
  body: "Hi Team The graphic engine and grid is getting some love lately and we will look into a future where gradient + image fill and non-rectangular clipping is available on the devices that supports it. I think both have interest from the ggplot2 side. While we are not there yet, @pmur002 has a working implementation and I think we may just as well begin discussing to what extend and how we may use this in ggplot2. I think the most interesting (seeing as ggpattern exist) possibility is gradient fill. This will most definitely be a challenge to integrate into the scale system because gradients depend on multiple values. Should the scaling happen from discrete values to a set of predefined gradients? or should each stop be mapped to different values. Lots of things to discuss! Non-rectangular clipping also opens up a lot of possibilities, some not having a clear parallel in the current API (e.g. clipping groups or layers to certain areas) @clauswilke @karawoo @Hadley @yutannihilation @paleolimbot please join the discussion 🙂"
  },
  {
  url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3996",
  repository_url: "https://api.github.com/repos/tidyverse/ggplot2",
  labels_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3996/labels{/name}",
  comments_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3996/comments",
  events_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3996/events",
  html_url: "https://github.com/tidyverse/ggplot2/pull/3996",
  id: 618759387,
  node_id: "MDExOlB1bGxSZXF1ZXN0NDE4NDIzODcw",
  number: 3996,
  title: "Fix #3995 export scale_alpha_binned",
  user: {
  login: "thomasp85",
  id: 1775316,
  node_id: "MDQ6VXNlcjE3NzUzMTY=",
  avatar_url: "https://avatars3.githubusercontent.com/u/1775316?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/thomasp85",
  html_url: "https://github.com/thomasp85",
  followers_url: "https://api.github.com/users/thomasp85/followers",
  following_url: "https://api.github.com/users/thomasp85/following{/other_user}",
  gists_url: "https://api.github.com/users/thomasp85/gists{/gist_id}",
  starred_url: "https://api.github.com/users/thomasp85/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/thomasp85/subscriptions",
  organizations_url: "https://api.github.com/users/thomasp85/orgs",
  repos_url: "https://api.github.com/users/thomasp85/repos",
  events_url: "https://api.github.com/users/thomasp85/events{/privacy}",
  received_events_url: "https://api.github.com/users/thomasp85/received_events",
  type: "User",
  site_admin: false
  },
  labels: [ ],
  state: "open",
  locked: false,
  assignee: null,
  assignees: [ ],
  milestone: {
  url: "https://api.github.com/repos/tidyverse/ggplot2/milestones/21",
  html_url: "https://github.com/tidyverse/ggplot2/milestone/21",
  labels_url: "https://api.github.com/repos/tidyverse/ggplot2/milestones/21/labels",
  id: 5181145,
  node_id: "MDk6TWlsZXN0b25lNTE4MTE0NQ==",
  number: 21,
  title: "ggplot2 3.3.1",
  description: "This will be a small patch release fixing regressions, improving performance, and folding in TDD PRs",
  creator: {
  login: "thomasp85",
  id: 1775316,
  node_id: "MDQ6VXNlcjE3NzUzMTY=",
  avatar_url: "https://avatars3.githubusercontent.com/u/1775316?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/thomasp85",
  html_url: "https://github.com/thomasp85",
  followers_url: "https://api.github.com/users/thomasp85/followers",
  following_url: "https://api.github.com/users/thomasp85/following{/other_user}",
  gists_url: "https://api.github.com/users/thomasp85/gists{/gist_id}",
  starred_url: "https://api.github.com/users/thomasp85/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/thomasp85/subscriptions",
  organizations_url: "https://api.github.com/users/thomasp85/orgs",
  repos_url: "https://api.github.com/users/thomasp85/repos",
  events_url: "https://api.github.com/users/thomasp85/events{/privacy}",
  received_events_url: "https://api.github.com/users/thomasp85/received_events",
  type: "User",
  site_admin: false
  },
  open_issues: 10,
  closed_issues: 34,
  state: "open",
  created_at: "2020-03-09T08:30:16Z",
  updated_at: "2020-05-16T17:04:24Z",
  due_on: null,
  closed_at: null
  },
  comments: 0,
  created_at: "2020-05-15T07:27:32Z",
  updated_at: "2020-05-15T18:26:52Z",
  closed_at: null,
  author_association: "MEMBER",
  pull_request: {
  url: "https://api.github.com/repos/tidyverse/ggplot2/pulls/3996",
  html_url: "https://github.com/tidyverse/ggplot2/pull/3996",
  diff_url: "https://github.com/tidyverse/ggplot2/pull/3996.diff",
  patch_url: "https://github.com/tidyverse/ggplot2/pull/3996.patch"
  },
  body: "Fix #3995 This PR also includes some unrelated data doc formatting changes due to a roxygen update"
  },
  {
  url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3995",
  repository_url: "https://api.github.com/repos/tidyverse/ggplot2",
  labels_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3995/labels{/name}",
  comments_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3995/comments",
  events_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3995/events",
  html_url: "https://github.com/tidyverse/ggplot2/issues/3995",
  id: 618453492,
  node_id: "MDU6SXNzdWU2MTg0NTM0OTI=",
  number: 3995,
  title: "scale_alpha_binned not exported",
  user: {
  login: "mdhall272",
  id: 1931652,
  node_id: "MDQ6VXNlcjE5MzE2NTI=",
  avatar_url: "https://avatars3.githubusercontent.com/u/1931652?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/mdhall272",
  html_url: "https://github.com/mdhall272",
  followers_url: "https://api.github.com/users/mdhall272/followers",
  following_url: "https://api.github.com/users/mdhall272/following{/other_user}",
  gists_url: "https://api.github.com/users/mdhall272/gists{/gist_id}",
  starred_url: "https://api.github.com/users/mdhall272/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/mdhall272/subscriptions",
  organizations_url: "https://api.github.com/users/mdhall272/orgs",
  repos_url: "https://api.github.com/users/mdhall272/repos",
  events_url: "https://api.github.com/users/mdhall272/events{/privacy}",
  received_events_url: "https://api.github.com/users/mdhall272/received_events",
  type: "User",
  site_admin: false
  },
  labels: [ ],
  state: "open",
  locked: false,
  assignee: null,
  assignees: [ ],
  milestone: {
  url: "https://api.github.com/repos/tidyverse/ggplot2/milestones/21",
  html_url: "https://github.com/tidyverse/ggplot2/milestone/21",
  labels_url: "https://api.github.com/repos/tidyverse/ggplot2/milestones/21/labels",
  id: 5181145,
  node_id: "MDk6TWlsZXN0b25lNTE4MTE0NQ==",
  number: 21,
  title: "ggplot2 3.3.1",
  description: "This will be a small patch release fixing regressions, improving performance, and folding in TDD PRs",
  creator: {
  login: "thomasp85",
  id: 1775316,
  node_id: "MDQ6VXNlcjE3NzUzMTY=",
  avatar_url: "https://avatars3.githubusercontent.com/u/1775316?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/thomasp85",
  html_url: "https://github.com/thomasp85",
  followers_url: "https://api.github.com/users/thomasp85/followers",
  following_url: "https://api.github.com/users/thomasp85/following{/other_user}",
  gists_url: "https://api.github.com/users/thomasp85/gists{/gist_id}",
  starred_url: "https://api.github.com/users/thomasp85/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/thomasp85/subscriptions",
  organizations_url: "https://api.github.com/users/thomasp85/orgs",
  repos_url: "https://api.github.com/users/thomasp85/repos",
  events_url: "https://api.github.com/users/thomasp85/events{/privacy}",
  received_events_url: "https://api.github.com/users/thomasp85/received_events",
  type: "User",
  site_admin: false
  },
  open_issues: 10,
  closed_issues: 34,
  state: "open",
  created_at: "2020-03-09T08:30:16Z",
  updated_at: "2020-05-16T17:04:24Z",
  due_on: null,
  closed_at: null
  },
  comments: 1,
  created_at: "2020-05-14T18:39:26Z",
  updated_at: "2020-05-14T19:23:42Z",
  closed_at: null,
  author_association: "NONE",
  body: "It looks like scale_alpha_binned is missing from the NAMESPACE despite being documented:"
  },
  {
  url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3994",
  repository_url: "https://api.github.com/repos/tidyverse/ggplot2",
  labels_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3994/labels{/name}",
  comments_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3994/comments",
  events_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3994/events",
  html_url: "https://github.com/tidyverse/ggplot2/issues/3994",
  id: 617555089,
  node_id: "MDU6SXNzdWU2MTc1NTUwODk=",
  number: 3994,
  title: "Drop plot_env from ggplot2 objects?",
  user: {
  login: "clauswilke",
  id: 4210929,
  node_id: "MDQ6VXNlcjQyMTA5Mjk=",
  avatar_url: "https://avatars2.githubusercontent.com/u/4210929?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/clauswilke",
  html_url: "https://github.com/clauswilke",
  followers_url: "https://api.github.com/users/clauswilke/followers",
  following_url: "https://api.github.com/users/clauswilke/following{/other_user}",
  gists_url: "https://api.github.com/users/clauswilke/gists{/gist_id}",
  starred_url: "https://api.github.com/users/clauswilke/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/clauswilke/subscriptions",
  organizations_url: "https://api.github.com/users/clauswilke/orgs",
  repos_url: "https://api.github.com/users/clauswilke/repos",
  events_url: "https://api.github.com/users/clauswilke/events{/privacy}",
  received_events_url: "https://api.github.com/users/clauswilke/received_events",
  type: "User",
  site_admin: false
  },
  labels: [ ],
  state: "open",
  locked: false,
  assignee: null,
  assignees: [ ],
  milestone: null,
  comments: 12,
  created_at: "2020-05-13T15:41:58Z",
  updated_at: "2020-05-15T22:16:19Z",
  closed_at: null,
  author_association: "MEMBER",
  body: "This comment https://github.com/tidyverse/ggplot2/issues/3619#issuecomment-628021555 prompted me to look into `plot_env`, and as far as I can see it's stored and handed around just so it can be eventually given to the function `combine_vars()`, which then doesn't use it: https://github.com/tidyverse/ggplot2/blob/e9b9946786dae861dea1c352f2ac7b2a837b5f82/R/facet-.r#L544-L587 Is this a hold-over from the times before tidy eval? Can we remove this/or assign `NULL` here? https://github.com/tidyverse/ggplot2/blob/5a686c34b304ddefeee16d44362f326cfa29634e/R/plot.r#L96 It is already marked as deprecated in the documentation: https://github.com/tidyverse/ggplot2/blob/5a686c34b304ddefeee16d44362f326cfa29634e/R/plot.r#L35 "
  },
  {
  url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3989",
  repository_url: "https://api.github.com/repos/tidyverse/ggplot2",
  labels_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3989/labels{/name}",
  comments_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3989/comments",
  events_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3989/events",
  html_url: "https://github.com/tidyverse/ggplot2/issues/3989",
  id: 614024331,
  node_id: "MDU6SXNzdWU2MTQwMjQzMzE=",
  number: 3989,
  title: "No option to justify within legend",
  user: {
  login: "py9mrg",
  id: 12600721,
  node_id: "MDQ6VXNlcjEyNjAwNzIx",
  avatar_url: "https://avatars0.githubusercontent.com/u/12600721?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/py9mrg",
  html_url: "https://github.com/py9mrg",
  followers_url: "https://api.github.com/users/py9mrg/followers",
  following_url: "https://api.github.com/users/py9mrg/following{/other_user}",
  gists_url: "https://api.github.com/users/py9mrg/gists{/gist_id}",
  starred_url: "https://api.github.com/users/py9mrg/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/py9mrg/subscriptions",
  organizations_url: "https://api.github.com/users/py9mrg/orgs",
  repos_url: "https://api.github.com/users/py9mrg/repos",
  events_url: "https://api.github.com/users/py9mrg/events{/privacy}",
  received_events_url: "https://api.github.com/users/py9mrg/received_events",
  type: "User",
  site_admin: false
  },
  labels: [ ],
  state: "open",
  locked: false,
  assignee: null,
  assignees: [ ],
  milestone: null,
  comments: 2,
  created_at: "2020-05-07T12:37:36Z",
  updated_at: "2020-05-08T14:14:04Z",
  closed_at: null,
  author_association: "NONE",
  body: "I'm trying to justify *everything* within a legend, but there appe"
  },
  {
  url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3988",
  repository_url: "https://api.github.com/repos/tidyverse/ggplot2",
  labels_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3988/labels{/name}",
  comments_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3988/comments",
  events_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3988/events",
  html_url: "https://github.com/tidyverse/ggplot2/issues/3988",
  id: 613429720,
  node_id: "MDU6SXNzdWU2MTM0Mjk3MjA=",
  number: 3988,
  title: "Aligning plots: Implementation of drop = FALSE for position_dodge",
  user: {
  login: "char4816",
  id: 40525022,
  node_id: "MDQ6VXNlcjQwNTI1MDIy",
  avatar_url: "https://avatars2.githubusercontent.com/u/40525022?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/char4816",
  html_url: "https://github.com/char4816",
  followers_url: "https://api.github.com/users/char4816/followers",
  following_url: "https://api.github.com/users/char4816/following{/other_user}",
  gists_url: "https://api.github.com/users/char4816/gists{/gist_id}",
  starred_url: "https://api.github.com/users/char4816/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/char4816/subscriptions",
  organizations_url: "https://api.github.com/users/char4816/orgs",
  repos_url: "https://api.github.com/users/char4816/repos",
  events_url: "https://api.github.com/users/char4816/events{/privacy}",
  received_events_url: "https://api.github.com/users/char4816/received_events",
  type: "User",
  site_admin: false
  },
  labels: [ ],
  state: "open",
  locked: false,
  assignee: null,
  assignees: [ ],
  milestone: null,
  comments: 0,
  created_at: "2020-05-06T15:56:10Z",
  updated_at: "2020-05-06T16:05:00Z",
  closed_at: null,
  author_association: "NONE",
  body: "--- As others have pointed out (https://github.com/tidyvers"
  },
  {
  url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3987",
  repository_url: "https://api.github.com/repos/tidyverse/ggplot2",
  labels_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3987/labels{/name}",
  comments_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3987/comments",
  events_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3987/events",
  html_url: "https://github.com/tidyverse/ggplot2/issues/3987",
  id: 612717337,
  node_id: "MDU6SXNzdWU2MTI3MTczMzc=",
  number: 3987,
  title: "Feature request: scale_*_reverse() to work on all classes",
  user: {
  login: "jzadra",
  id: 25590353,
  node_id: "MDQ6VXNlcjI1NTkwMzUz",
  avatar_url: "https://avatars0.githubusercontent.com/u/25590353?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/jzadra",
  html_url: "https://github.com/jzadra",
  followers_url: "https://api.github.com/users/jzadra/followers",
  following_url: "https://api.github.com/users/jzadra/following{/other_user}",
  gists_url: "https://api.github.com/users/jzadra/gists{/gist_id}",
  starred_url: "https://api.github.com/users/jzadra/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/jzadra/subscriptions",
  organizations_url: "https://api.github.com/users/jzadra/orgs",
  repos_url: "https://api.github.com/users/jzadra/repos",
  events_url: "https://api.github.com/users/jzadra/events{/privacy}",
  received_events_url: "https://api.github.com/users/jzadra/received_events",
  type: "User",
  site_admin: false
  },
  labels: [ ],
  state: "open",
  locked: false,
  assignee: null,
  assignees: [ ],
  milestone: null,
  comments: 2,
  created_at: "2020-05-05T16:04:26Z",
  updated_at: "2020-05-13T13:15:24Z",
  closed_at: null,
  author_association: "NONE",
  body: "scale_*_reverse() currently only works on numeric. It would be great if it would work on factors and character classes as well, as currently several extra bits of code have to be used to accomplish this, and that code also doesn't work with rlang references."
  },
  {
  url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3986",
  repository_url: "https://api.github.com/repos/tidyverse/ggplot2",
  labels_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3986/labels{/name}",
  comments_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3986/comments",
  events_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3986/events",
  html_url: "https://github.com/tidyverse/ggplot2/issues/3986",
  id: 612616038,
  node_id: "MDU6SXNzdWU2MTI2MTYwMzg=",
  number: 3986,
  title: "Missing generic `+` method",
  user: {
  login: "schloerke",
  id: 93231,
  node_id: "MDQ6VXNlcjkzMjMx",
  avatar_url: "https://avatars1.githubusercontent.com/u/93231?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/schloerke",
  html_url: "https://github.com/schloerke",
  followers_url: "https://api.github.com/users/schloerke/followers",
  following_url: "https://api.github.com/users/schloerke/following{/other_user}",
  gists_url: "https://api.github.com/users/schloerke/gists{/gist_id}",
  starred_url: "https://api.github.com/users/schloerke/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/schloerke/subscriptions",
  organizations_url: "https://api.github.com/users/schloerke/orgs",
  repos_url: "https://api.github.com/users/schloerke/repos",
  events_url: "https://api.github.com/users/schloerke/events{/privacy}",
  received_events_url: "https://api.github.com/users/schloerke/received_events",
  type: "User",
  site_admin: false
  },
  labels: [ ],
  state: "open",
  locked: false,
  assignee: null,
  assignees: [ ],
  milestone: null,
  comments: 0,
  created_at: "2020-05-05T13:46:50Z",
  updated_at: "2020-05-05T13:46:50Z",
  closed_at: null,
  author_association: "CONTRIBUTOR",
  body: "(cc @clauswilke https://github.com/tidyverse/ggplot2/pull/3818#issuecomment-623055651) "
  },
  {
  url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3985",
  repository_url: "https://api.github.com/repos/tidyverse/ggplot2",
  labels_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3985/labels{/name}",
  comments_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3985/comments",
  events_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3985/events",
  html_url: "https://github.com/tidyverse/ggplot2/issues/3985",
  id: 611852206,
  node_id: "MDU6SXNzdWU2MTE4NTIyMDY=",
  number: 3985,
  title: "Hint to where to alter within ggplot (for extension)",
  user: {
  login: "Athanasiamo",
  id: 14014329,
  node_id: "MDQ6VXNlcjE0MDE0MzI5",
  avatar_url: "https://avatars3.githubusercontent.com/u/14014329?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Athanasiamo",
  html_url: "https://github.com/Athanasiamo",
  followers_url: "https://api.github.com/users/Athanasiamo/followers",
  following_url: "https://api.github.com/users/Athanasiamo/following{/other_user}",
  gists_url: "https://api.github.com/users/Athanasiamo/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Athanasiamo/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Athanasiamo/subscriptions",
  organizations_url: "https://api.github.com/users/Athanasiamo/orgs",
  repos_url: "https://api.github.com/users/Athanasiamo/repos",
  events_url: "https://api.github.com/users/Athanasiamo/events{/privacy}",
  received_events_url: "https://api.github.com/users/Athanasiamo/received_events",
  type: "User",
  site_admin: false
  },
  labels: [ ],
  state: "open",
  locked: false,
  assignee: null,
  assignees: [ ],
  milestone: null,
  comments: 0,
  created_at: "2020-05-04T12:52:35Z",
  updated_at: "2020-05-04T12:52:35Z",
  closed_at: null,
  author_association: "NONE",
  body: "Hi. I've been trying to figure this out for quite some time "
  },
  {
  url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3980",
  repository_url: "https://api.github.com/repos/tidyverse/ggplot2",
  labels_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3980/labels{/name}",
  comments_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3980/comments",
  events_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3980/events",
  html_url: "https://github.com/tidyverse/ggplot2/pull/3980",
  id: 610699247,
  node_id: "MDExOlB1bGxSZXF1ZXN0NDEyMDkwMTU2",
  number: 3980,
  title: "specific behavior of geom_dotplot()",
  user: {
  login: "gael-millot",
  id: 61543802,
  node_id: "MDQ6VXNlcjYxNTQzODAy",
  avatar_url: "https://avatars0.githubusercontent.com/u/61543802?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/gael-millot",
  html_url: "https://github.com/gael-millot",
  followers_url: "https://api.github.com/users/gael-millot/followers",
  following_url: "https://api.github.com/users/gael-millot/following{/other_user}",
  gists_url: "https://api.github.com/users/gael-millot/gists{/gist_id}",
  starred_url: "https://api.github.com/users/gael-millot/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/gael-millot/subscriptions",
  organizations_url: "https://api.github.com/users/gael-millot/orgs",
  repos_url: "https://api.github.com/users/gael-millot/repos",
  events_url: "https://api.github.com/users/gael-millot/events{/privacy}",
  received_events_url: "https://api.github.com/users/gael-millot/received_events",
  type: "User",
  site_admin: false
  },
  labels: [ ],
  state: "open",
  locked: false,
  assignee: null,
  assignees: [ ],
  milestone: null,
  comments: 0,
  created_at: "2020-05-01T11:10:02Z",
  updated_at: "2020-05-01T11:10:02Z",
  closed_at: null,
  author_association: "NONE",
  pull_request: {
  url: "https://api.github.com/repos/tidyverse/ggplot2/pulls/3980",
  html_url: "https://github.com/tidyverse/ggplot2/pull/3980",
  diff_url: "https://github.com/tidyverse/ggplot2/pull/3980.diff",
  patch_url: "https://github.com/tidyverse/ggplot2/pull/3980.patch"
  },
  body: "news examples that include the specific behavior of geom_dotplot()"
  },
  {
  url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3975",
  repository_url: "https://api.github.com/repos/tidyverse/ggplot2",
  labels_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3975/labels{/name}",
  comments_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3975/comments",
  events_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3975/events",
  html_url: "https://github.com/tidyverse/ggplot2/issues/3975",
  id: 610422326,
  node_id: "MDU6SXNzdWU2MTA0MjIzMjY=",
  number: 3975,
  title: "Panel scale initialisation before transformation",
  user: {
  login: "teunbrand",
  id: 49372158,
  node_id: "MDQ6VXNlcjQ5MzcyMTU4",
  avatar_url: "https://avatars3.githubusercontent.com/u/49372158?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/teunbrand",
  html_url: "https://github.com/teunbrand",
  followers_url: "https://api.github.com/users/teunbrand/followers",
  following_url: "https://api.github.com/users/teunbrand/following{/other_user}",
  gists_url: "https://api.github.com/users/teunbrand/gists{/gist_id}",
  starred_url: "https://api.github.com/users/teunbrand/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/teunbrand/subscriptions",
  organizations_url: "https://api.github.com/users/teunbrand/orgs",
  repos_url: "https://api.github.com/users/teunbrand/repos",
  events_url: "https://api.github.com/users/teunbrand/events{/privacy}",
  received_events_url: "https://api.github.com/users/teunbrand/received_events",
  type: "User",
  site_admin: false
  },
  labels: [ ],
  state: "open",
  locked: false,
  assignee: null,
  assignees: [ ],
  milestone: null,
  comments: 0,
  created_at: "2020-04-30T22:15:02Z",
  updated_at: "2020-04-30T22:15:02Z",
  closed_at: null,
  author_association: "CONTRIBUTOR",
  body: "Hi all, I was wondering whether"
  },
  {
  url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3973",
  repository_url: "https://api.github.com/repos/tidyverse/ggplot2",
  labels_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3973/labels{/name}",
  comments_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3973/comments",
  events_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3973/events",
  html_url: "https://github.com/tidyverse/ggplot2/pull/3973",
  id: 609390025,
  node_id: "MDExOlB1bGxSZXF1ZXN0NDEwOTc3NTQx",
  number: 3973,
  title: "WIP: Register default scales via themes ",
  user: {
  login: "Alanocallaghan",
  id: 10779688,
  node_id: "MDQ6VXNlcjEwNzc5Njg4",
  avatar_url: "https://avatars2.githubusercontent.com/u/10779688?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Alanocallaghan",
  html_url: "https://github.com/Alanocallaghan",
  followers_url: "https://api.github.com/users/Alanocallaghan/followers",
  following_url: "https://api.github.com/users/Alanocallaghan/following{/other_user}",
  gists_url: "https://api.github.com/users/Alanocallaghan/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Alanocallaghan/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Alanocallaghan/subscriptions",
  organizations_url: "https://api.github.com/users/Alanocallaghan/orgs",
  repos_url: "https://api.github.com/users/Alanocallaghan/repos",
  events_url: "https://api.github.com/users/Alanocallaghan/events{/privacy}",
  received_events_url: "https://api.github.com/users/Alanocallaghan/received_events",
  type: "User",
  site_admin: false
  },
  labels: [ ],
  state: "open",
  locked: false,
  assignee: null,
  assignees: [ ],
  milestone: null,
  comments: 4,
  created_at: "2020-04-29T22:03:38Z",
  updated_at: "2020-04-30T14:18:19Z",
  closed_at: null,
  author_association: "NONE",
  pull_request: {
  url: "https://api.github.com/repos/tidyverse/ggplot2/pulls/3973",
  html_url: "https://github.com/tidyverse/ggplot2/pull/3973",
  diff_url: "https://github.com/tidyverse/ggplot2/pull/3973.diff",
  patch_url: "https://github.com/tidyverse/ggplot2/pull/3973.patch"
  },
  body: "Resolve #2691 Add `default.scales` component of themes."
  },
  {
  url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3972",
  repository_url: "https://api.github.com/repos/tidyverse/ggplot2",
  labels_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3972/labels{/name}",
  comments_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3972/comments",
  events_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3972/events",
  html_url: "https://github.com/tidyverse/ggplot2/pull/3972",
  id: 608816150,
  node_id: "MDExOlB1bGxSZXF1ZXN0NDEwNTIwNDkw",
  number: 3972,
  title: "WIP: Support guide_axis() on all Coord",
  user: {
  login: "yutannihilation",
  id: 1978793,
  node_id: "MDQ6VXNlcjE5Nzg3OTM=",
  avatar_url: "https://avatars3.githubusercontent.com/u/1978793?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/yutannihilation",
  html_url: "https://github.com/yutannihilation",
  followers_url: "https://api.github.com/users/yutannihilation/followers",
  following_url: "https://api.github.com/users/yutannihilation/following{/other_user}",
  gists_url: "https://api.github.com/users/yutannihilation/gists{/gist_id}",
  starred_url: "https://api.github.com/users/yutannihilation/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/yutannihilation/subscriptions",
  organizations_url: "https://api.github.com/users/yutannihilation/orgs",
  repos_url: "https://api.github.com/users/yutannihilation/repos",
  events_url: "https://api.github.com/users/yutannihilation/events{/privacy}",
  received_events_url: "https://api.github.com/users/yutannihilation/received_events",
  type: "User",
  site_admin: false
  },
  labels: [ ],
  state: "open",
  locked: false,
  assignee: null,
  assignees: [ ],
  milestone: null,
  comments: 4,
  created_at: "2020-04-29T06:41:11Z",
  updated_at: "2020-05-15T07:53:11Z",
  closed_at: null,
  author_association: "MEMBER",
  pull_request: {
  url: "https://api.github.com/repos/tidyverse/ggplot2/pulls/3972",
  html_url: "https://github.com/tidyverse/ggplot2/pull/3972",
  diff_url: "https://github.com/tidyverse/ggplot2/pull/3972.diff",
  patch_url: "https://github.com/tidyverse/ggplot2/pull/3972.patch"
  },
  body: "Fixes #3959 -"
  },
  {
  url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3965",
  repository_url: "https://api.github.com/repos/tidyverse/ggplot2",
  labels_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3965/labels{/name}",
  comments_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3965/comments",
  events_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3965/events",
  html_url: "https://github.com/tidyverse/ggplot2/issues/3965",
  id: 606971238,
  node_id: "MDU6SXNzdWU2MDY5NzEyMzg=",
  number: 3965,
  title: "Misaligned date axis for some custom breaks functions",
  user: {
  login: "geotheory",
  id: 1282581,
  node_id: "MDQ6VXNlcjEyODI1ODE=",
  avatar_url: "https://avatars1.githubusercontent.com/u/1282581?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/geotheory",
  html_url: "https://github.com/geotheory",
  followers_url: "https://api.github.com/users/geotheory/followers",
  following_url: "https://api.github.com/users/geotheory/following{/other_user}",
  gists_url: "https://api.github.com/users/geotheory/gists{/gist_id}",
  starred_url: "https://api.github.com/users/geotheory/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/geotheory/subscriptions",
  organizations_url: "https://api.github.com/users/geotheory/orgs",
  repos_url: "https://api.github.com/users/geotheory/repos",
  events_url: "https://api.github.com/users/geotheory/events{/privacy}",
  received_events_url: "https://api.github.com/users/geotheory/received_events",
  type: "User",
  site_admin: false
  },
  labels: [
  {
  id: 17279,
  node_id: "MDU6TGFiZWwxNzI3OQ==",
  url: "https://api.github.com/repos/tidyverse/ggplot2/labels/bug",
  name: "bug",
  color: "E0B3A2",
  default: true,
  description: "an unexpected problem or unintended behavior"
  },
  {
  id: 526758072,
  node_id: "MDU6TGFiZWw1MjY3NTgwNzI=",
  url: "https://api.github.com/repos/tidyverse/ggplot2/labels/scales%20:snake:",
  name: "scales :snake:",
  color: "eeeeee",
  default: false,
  description: ""
  }
  ],
  state: "open",
  locked: false,
  assignee: null,
  assignees: [ ],
  milestone: null,
  comments: 1,
  created_at: "2020-04-26T09:56:49Z",
  updated_at: "2020-04-30T18:18:07Z",
  closed_at: null,
  author_association: "NONE",
  body: "A custom breaks function on the date axis s"
  },
  {
  url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3962",
  repository_url: "https://api.github.com/repos/tidyverse/ggplot2",
  labels_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3962/labels{/name}",
  comments_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3962/comments",
  events_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3962/events",
  html_url: "https://github.com/tidyverse/ggplot2/issues/3962",
  id: 606832128,
  node_id: "MDU6SXNzdWU2MDY4MzIxMjg=",
  number: 3962,
  title: "Shortcut for `scale_y_continuous(expand = expansion(c(0, 0.05))`",
  user: {
  login: "thomas-neitmann",
  id: 11788080,
  node_id: "MDQ6VXNlcjExNzg4MDgw",
  avatar_url: "https://avatars2.githubusercontent.com/u/11788080?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/thomas-neitmann",
  html_url: "https://github.com/thomas-neitmann",
  followers_url: "https://api.github.com/users/thomas-neitmann/followers",
  following_url: "https://api.github.com/users/thomas-neitmann/following{/other_user}",
  gists_url: "https://api.github.com/users/thomas-neitmann/gists{/gist_id}",
  starred_url: "https://api.github.com/users/thomas-neitmann/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/thomas-neitmann/subscriptions",
  organizations_url: "https://api.github.com/users/thomas-neitmann/orgs",
  repos_url: "https://api.github.com/users/thomas-neitmann/repos",
  events_url: "https://api.github.com/users/thomas-neitmann/events{/privacy}",
  received_events_url: "https://api.github.com/users/thomas-neitmann/received_events",
  type: "User",
  site_admin: false
  },
  labels: [
  {
  id: 88457590,
  node_id: "MDU6TGFiZWw4ODQ1NzU5MA==",
  url: "https://api.github.com/repos/tidyverse/ggplot2/labels/feature",
  name: "feature",
  color: "B4C3AE",
  default: false,
  description: "a feature request or enhancement"
  },
  {
  id: 526758072,
  node_id: "MDU6TGFiZWw1MjY3NTgwNzI=",
  url: "https://api.github.com/repos/tidyverse/ggplot2/labels/scales%20:snake:",
  name: "scales :snake:",
  color: "eeeeee",
  default: false,
  description: ""
  }
  ],
  state: "open",
  locked: false,
  assignee: null,
  assignees: [ ],
  milestone: null,
  comments: 3,
  created_at: "2020-04-25T18:49:59Z",
  updated_at: "2020-04-30T18:18:59Z",
  closed_at: null,
  author_association: "NONE",
  body: "When creating histogram or bar charts the sta",
  },
  {
  url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3959",
  repository_url: "https://api.github.com/repos/tidyverse/ggplot2",
  labels_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3959/labels{/name}",
  comments_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3959/comments",
  events_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3959/events",
  html_url: "https://github.com/tidyverse/ggplot2/issues/3959",
  id: 605079717,
  node_id: "MDU6SXNzdWU2MDUwNzk3MTc=",
  number: 3959,
  title: "coord_trans/polar() ignore position guides",
  user: {
  login: "teunbrand",
  id: 49372158,
  node_id: "MDQ6VXNlcjQ5MzcyMTU4",
  avatar_url: "https://avatars3.githubusercontent.com/u/49372158?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/teunbrand",
  html_url: "https://github.com/teunbrand",
  followers_url: "https://api.github.com/users/teunbrand/followers",
  following_url: "https://api.github.com/users/teunbrand/following{/other_user}",
  gists_url: "https://api.github.com/users/teunbrand/gists{/gist_id}",
  starred_url: "https://api.github.com/users/teunbrand/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/teunbrand/subscriptions",
  organizations_url: "https://api.github.com/users/teunbrand/orgs",
  repos_url: "https://api.github.com/users/teunbrand/repos",
  events_url: "https://api.github.com/users/teunbrand/events{/privacy}",
  received_events_url: "https://api.github.com/users/teunbrand/received_events",
  type: "User",
  site_admin: false
  },
  labels: [
  {
  id: 538487763,
  node_id: "MDU6TGFiZWw1Mzg0ODc3NjM=",
  url: "https://api.github.com/repos/tidyverse/ggplot2/labels/coord%20:world_map:",
  name: "coord :world_map:",
  color: "eeeeee",
  default: false,
  description: ""
  },
  {
  id: 1375682772,
  node_id: "MDU6TGFiZWwxMzc1NjgyNzcy",
  url: "https://api.github.com/repos/tidyverse/ggplot2/labels/guides%20:straight_ruler:",
  name: "guides :straight_ruler:",
  color: "eeeeee",
  default: false,
  description: ""
  }
  ],
  state: "open",
  locked: false,
  assignee: null,
  assignees: [ ],
  milestone: null,
  comments: 3,
  created_at: "2020-04-22T21:14:31Z",
  updated_at: "2020-04-30T18:22:53Z",
  closed_at: null,
  author_association: "CONTRIBUTOR",
  body: "While I was tr"
  },
  {
  url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3956",
  repository_url: "https://api.github.com/repos/tidyverse/ggplot2",
  labels_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3956/labels{/name}",
  comments_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3956/comments",
  events_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3956/events",
  html_url: "https://github.com/tidyverse/ggplot2/issues/3956",
  id: 603635024,
  node_id: "MDU6SXNzdWU2MDM2MzUwMjQ=",
  number: 3956,
  title: "Remove stat and position arguments from qplot() and formaly deprecate the function",
  user: {
  login: "yutannihilation",
  id: 1978793,
  node_id: "MDQ6VXNlcjE5Nzg3OTM=",
  avatar_url: "https://avatars3.githubusercontent.com/u/1978793?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/yutannihilation",
  html_url: "https://github.com/yutannihilation",
  followers_url: "https://api.github.com/users/yutannihilation/followers",
  following_url: "https://api.github.com/users/yutannihilation/following{/other_user}",
  gists_url: "https://api.github.com/users/yutannihilation/gists{/gist_id}",
  starred_url: "https://api.github.com/users/yutannihilation/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/yutannihilation/subscriptions",
  organizations_url: "https://api.github.com/users/yutannihilation/orgs",
  repos_url: "https://api.github.com/users/yutannihilation/repos",
  events_url: "https://api.github.com/users/yutannihilation/events{/privacy}",
  received_events_url: "https://api.github.com/users/yutannihilation/received_events",
  type: "User",
  site_admin: false
  },
  labels: [
  {
  id: 1027412031,
  node_id: "MDU6TGFiZWwxMDI3NDEyMDMx",
  url: "https://api.github.com/repos/tidyverse/ggplot2/labels/API%20change%20%F0%9F%98%88",
  name: "API change 😈",
  color: "000000",
  default: false,
  description: ""
  }
  ],
  state: "open",
  locked: false,
  assignee: null,
  assignees: [ ],
  milestone: {
  url: "https://api.github.com/repos/tidyverse/ggplot2/milestones/20",
  html_url: "https://github.com/tidyverse/ggplot2/milestone/20",
  labels_url: "https://api.github.com/repos/tidyverse/ggplot2/milestones/20/labels",
  id: 5080355,
  node_id: "MDk6TWlsZXN0b25lNTA4MDM1NQ==",
  number: 20,
  title: "ggplot2 3.4.0",
  description: "Next release after 3.3.0. Tentatively called 3.4.0.",
  creator: {
  login: "clauswilke",
  id: 4210929,
  node_id: "MDQ6VXNlcjQyMTA5Mjk=",
  avatar_url: "https://avatars2.githubusercontent.com/u/4210929?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/clauswilke",
  html_url: "https://github.com/clauswilke",
  followers_url: "https://api.github.com/users/clauswilke/followers",
  following_url: "https://api.github.com/users/clauswilke/following{/other_user}",
  gists_url: "https://api.github.com/users/clauswilke/gists{/gist_id}",
  starred_url: "https://api.github.com/users/clauswilke/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/clauswilke/subscriptions",
  organizations_url: "https://api.github.com/users/clauswilke/orgs",
  repos_url: "https://api.github.com/users/clauswilke/repos",
  events_url: "https://api.github.com/users/clauswilke/events{/privacy}",
  received_events_url: "https://api.github.com/users/clauswilke/received_events",
  type: "User",
  site_admin: false
  },
  open_issues: 10,
  closed_issues: 0,
  state: "open",
  created_at: "2020-02-07T01:33:01Z",
  updated_at: "2020-04-29T20:00:30Z",
  due_on: null,
  closed_at: null
  },
  comments: 4,
  created_at: "2020-04-21T01:18:15Z",
  updated_at: "2020-05-06T03:24:07Z",
  closed_at: null,
  author_association: "MEMBER",
  body: "`stat` and `position` were deprecated 4.5 years ago ([v2.0.0](https://ggplot2.tidyverse.org/news/index.html#deprecated-features)), so I think it's time to remove them. I think we have no development bandwidth to fix such tricky bugs like https://github.com/tidyverse/ggplot2/issues/3670. Also, can we agree on deprecating `qplot()` itself? Though we've never discussed this formally, I believe the use of `qplot()` is discouraged, which virtually means it's deprecated."
  },
  {
  url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3954",
  repository_url: "https://api.github.com/repos/tidyverse/ggplot2",
  labels_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3954/labels{/name}",
  comments_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3954/comments",
  events_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3954/events",
  html_url: "https://github.com/tidyverse/ggplot2/issues/3954",
  id: 602892432,
  node_id: "MDU6SXNzdWU2MDI4OTI0MzI=",
  number: 3954,
  title: "conflict of `coord_flip()` with `annotation_logticks()`",
  user: {
  login: "DSLituiev",
  id: 8426290,
  node_id: "MDQ6VXNlcjg0MjYyOTA=",
  avatar_url: "https://avatars0.githubusercontent.com/u/8426290?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/DSLituiev",
  html_url: "https://github.com/DSLituiev",
  followers_url: "https://api.github.com/users/DSLituiev/followers",
  following_url: "https://api.github.com/users/DSLituiev/following{/other_user}",
  gists_url: "https://api.github.com/users/DSLituiev/gists{/gist_id}",
  starred_url: "https://api.github.com/users/DSLituiev/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/DSLituiev/subscriptions",
  organizations_url: "https://api.github.com/users/DSLituiev/orgs",
  repos_url: "https://api.github.com/users/DSLituiev/repos",
  events_url: "https://api.github.com/users/DSLituiev/events{/privacy}",
  received_events_url: "https://api.github.com/users/DSLituiev/received_events",
  type: "User",
  site_admin: false
  },
  labels: [
  {
  id: 17279,
  node_id: "MDU6TGFiZWwxNzI3OQ==",
  url: "https://api.github.com/repos/tidyverse/ggplot2/labels/bug",
  name: "bug",
  color: "E0B3A2",
  default: true,
  description: "an unexpected problem or unintended behavior"
  },
  {
  id: 538487763,
  node_id: "MDU6TGFiZWw1Mzg0ODc3NjM=",
  url: "https://api.github.com/repos/tidyverse/ggplot2/labels/coord%20:world_map:",
  name: "coord :world_map:",
  color: "eeeeee",
  default: false,
  description: ""
  },
  {
  id: 526758881,
  node_id: "MDU6TGFiZWw1MjY3NTg4ODE=",
  url: "https://api.github.com/repos/tidyverse/ggplot2/labels/layers%20:chart_with_upwards_trend:",
  name: "layers :chart_with_upwards_trend:",
  color: "eeeeee",
  default: false,
  description: ""
  }
  ],
  state: "open",
  locked: false,
  assignee: null,
  assignees: [ ],
  milestone: null,
  comments: 3,
  created_at: "2020-04-20T02:23:23Z",
  updated_at: "2020-04-30T18:26:28Z",
  closed_at: null,
  author_association: "NONE",
  body: "This behaves exactly like the closed issue #881, "
  },
  {
  url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3951",
  repository_url: "https://api.github.com/repos/tidyverse/ggplot2",
  labels_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3951/labels{/name}",
  comments_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3951/comments",
  events_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3951/events",
  html_url: "https://github.com/tidyverse/ggplot2/issues/3951",
  id: 602469488,
  node_id: "MDU6SXNzdWU2MDI0Njk0ODg=",
  number: 3951,
  title: "Suggestion: `rel`-class can inherit value from `unit`-class theme elements",
  user: {
  login: "teunbrand",
  id: 49372158,
  node_id: "MDQ6VXNlcjQ5MzcyMTU4",
  avatar_url: "https://avatars3.githubusercontent.com/u/49372158?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/teunbrand",
  html_url: "https://github.com/teunbrand",
  followers_url: "https://api.github.com/users/teunbrand/followers",
  following_url: "https://api.github.com/users/teunbrand/following{/other_user}",
  gists_url: "https://api.github.com/users/teunbrand/gists{/gist_id}",
  starred_url: "https://api.github.com/users/teunbrand/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/teunbrand/subscriptions",
  organizations_url: "https://api.github.com/users/teunbrand/orgs",
  repos_url: "https://api.github.com/users/teunbrand/repos",
  events_url: "https://api.github.com/users/teunbrand/events{/privacy}",
  received_events_url: "https://api.github.com/users/teunbrand/received_events",
  type: "User",
  site_admin: false
  },
  labels: [
  {
  id: 88457590,
  node_id: "MDU6TGFiZWw4ODQ1NzU5MA==",
  url: "https://api.github.com/repos/tidyverse/ggplot2/labels/feature",
  name: "feature",
  color: "B4C3AE",
  default: false,
  description: "a feature request or enhancement"
  },
  {
  id: 525885766,
  node_id: "MDU6TGFiZWw1MjU4ODU3NjY=",
  url: "https://api.github.com/repos/tidyverse/ggplot2/labels/themes%20:dancer:",
  name: "themes :dancer:",
  color: "eeeeee",
  default: false,
  description: ""
  }
  ],
  state: "open",
  locked: false,
  assignee: null,
  assignees: [ ],
  milestone: null,
  comments: 1,
  created_at: "2020-04-18T14:14:01Z",
  updated_at: "2020-04-30T18:35:11Z",
  closed_at: null,
  author_association: "CONTRIBUTOR",
  body: "I know `rel` objects are not really supported as theme elements on their own, but since the `size` argument in `element_line/rect/text()` can take a `rel` object and inherit the (modified) value from the parent, it doesn't seem like too far a stretch to have child `rel` theme elements. Suppose you'd like your legend keys to be half as tall as usual, it would be neat if you could do the following: ``` r library(ggplot2) ggplot(iris, aes(Sepal.Length, Sepal.Width)) + geom_point(aes(colour = Species)) + theme(legend.key.height = rel(0.5)) #> Error: Theme element `legend.key.height` must be an `unit` object. ``` <sup>Created on 2020-04-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup> I think it would require changes at these locations. * This check would have to allow `rel` classes for `unit` elements https://github.com/tidyverse/ggplot2/blob/7e6d1259237d9a2b48b8156e62ada2c47c411f31/R/theme.r#L530-L533 * This might need an extra logical branch for `rel`-`rel` and `rel`-`unit` elements https://github.com/tidyverse/ggplot2/blob/7e6d1259237d9a2b48b8156e62ada2c47c411f31/R/theme.r#L665-L668 * Don't allow `rel` objects as 'root'-nodes in the element tree. I think the most appropriate spot to do this would be in `validate_element()`. https://github.com/tidyverse/ggplot2/blob/40f67518a8d0ee8d7b6a1d1851c206656864fac8/R/theme-elements.r#L508 Thanks for considering!"
  },
  {
  url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3946",
  repository_url: "https://api.github.com/repos/tidyverse/ggplot2",
  labels_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3946/labels{/name}",
  comments_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3946/comments",
  events_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3946/events",
  html_url: "https://github.com/tidyverse/ggplot2/issues/3946",
  id: 598532952,
  node_id: "MDU6SXNzdWU1OTg1MzI5NTI=",
  number: 3946,
  title: "Add undocumented parameter o geom_density_2d docs",
  user: {
  login: "Fealthas",
  id: 25716039,
  node_id: "MDQ6VXNlcjI1NzE2MDM5",
  avatar_url: "https://avatars3.githubusercontent.com/u/25716039?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Fealthas",
  html_url: "https://github.com/Fealthas",
  followers_url: "https://api.github.com/users/Fealthas/followers",
  following_url: "https://api.github.com/users/Fealthas/following{/other_user}",
  gists_url: "https://api.github.com/users/Fealthas/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Fealthas/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Fealthas/subscriptions",
  organizations_url: "https://api.github.com/users/Fealthas/orgs",
  repos_url: "https://api.github.com/users/Fealthas/repos",
  events_url: "https://api.github.com/users/Fealthas/events{/privacy}",
  received_events_url: "https://api.github.com/users/Fealthas/received_events",
  type: "User",
  site_admin: false
  },
  labels: [
  {
  id: 119475,
  node_id: "MDU6TGFiZWwxMTk0NzU=",
  url: "https://api.github.com/repos/tidyverse/ggplot2/labels/documentation",
  name: "documentation",
  color: "CBBAB8",
  default: true,
  description: ""
  },
  {
  id: 914900944,
  node_id: "MDU6TGFiZWw5MTQ5MDA5NDQ=",
  url: "https://api.github.com/repos/tidyverse/ggplot2/labels/good%20first%20issue%20:heart:",
  name: "good first issue :heart:",
  color: "CBBAB8",
  default: false,
  description: "good issue for first-time contributors"
  }
  ],
  state: "open",
  locked: false,
  assignee: null,
  assignees: [ ],
  milestone: null,
  comments: 1,
  created_at: "2020-04-12T17:29:30Z",
  updated_at: "2020-04-30T18:35:45Z",
  closed_at: null,
  author_association: "NONE",
  body: "The parameter  in ``` geom_density_2d(aes(x,y) , bins=6)``` works as expected, but is not documented anywhere."
  },
  {
  url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3945",
  repository_url: "https://api.github.com/repos/tidyverse/ggplot2",
  labels_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3945/labels{/name}",
  comments_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3945/comments",
  events_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3945/events",
  html_url: "https://github.com/tidyverse/ggplot2/issues/3945",
  id: 598385260,
  node_id: "MDU6SXNzdWU1OTgzODUyNjA=",
  number: 3945,
  title: "Case of poor error message in PR #3659",
  user: {
  login: "clauswilke",
  id: 4210929,
  node_id: "MDQ6VXNlcjQyMTA5Mjk=",
  avatar_url: "https://avatars2.githubusercontent.com/u/4210929?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/clauswilke",
  html_url: "https://github.com/clauswilke",
  followers_url: "https://api.github.com/users/clauswilke/followers",
  following_url: "https://api.github.com/users/clauswilke/following{/other_user}",
  gists_url: "https://api.github.com/users/clauswilke/gists{/gist_id}",
  starred_url: "https://api.github.com/users/clauswilke/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/clauswilke/subscriptions",
  organizations_url: "https://api.github.com/users/clauswilke/orgs",
  repos_url: "https://api.github.com/users/clauswilke/repos",
  events_url: "https://api.github.com/users/clauswilke/events{/privacy}",
  received_events_url: "https://api.github.com/users/clauswilke/received_events",
  type: "User",
  site_admin: false
  },
  labels: [
  {
  id: 1802219789,
  node_id: "MDU6TGFiZWwxODAyMjE5Nzg5",
  url: "https://api.github.com/repos/tidyverse/ggplot2/labels/messages",
  name: "messages",
  color: "fef2c0",
  default: false,
  description: "requests for improvements to error, warning, or feedback messages"
  }
  ],
  state: "open",
  locked: false,
  assignee: null,
  assignees: [ ],
  milestone: {
  url: "https://api.github.com/repos/tidyverse/ggplot2/milestones/20",
  html_url: "https://github.com/tidyverse/ggplot2/milestone/20",
  labels_url: "https://api.github.com/repos/tidyverse/ggplot2/milestones/20/labels",
  id: 5080355,
  node_id: "MDk6TWlsZXN0b25lNTA4MDM1NQ==",
  number: 20,
  title: "ggplot2 3.4.0",
  description: "Next release after 3.3.0. Tentatively called 3.4.0.",
  creator: {
  login: "clauswilke",
  id: 4210929,
  node_id: "MDQ6VXNlcjQyMTA5Mjk=",
  avatar_url: "https://avatars2.githubusercontent.com/u/4210929?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/clauswilke",
  html_url: "https://github.com/clauswilke",
  followers_url: "https://api.github.com/users/clauswilke/followers",
  following_url: "https://api.github.com/users/clauswilke/following{/other_user}",
  gists_url: "https://api.github.com/users/clauswilke/gists{/gist_id}",
  starred_url: "https://api.github.com/users/clauswilke/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/clauswilke/subscriptions",
  organizations_url: "https://api.github.com/users/clauswilke/orgs",
  repos_url: "https://api.github.com/users/clauswilke/repos",
  events_url: "https://api.github.com/users/clauswilke/events{/privacy}",
  received_events_url: "https://api.github.com/users/clauswilke/received_events",
  type: "User",
  site_admin: false
  },
  open_issues: 10,
  closed_issues: 0,
  state: "open",
  created_at: "2020-02-07T01:33:01Z",
  updated_at: "2020-04-29T20:00:30Z",
  due_on: null,
  closed_at: null
  },
  comments: 0,
  created_at: "2020-04-12T01:17:28Z",
  updated_at: "2020-04-30T18:37:12Z",
  closed_at: null,
  author_association: "MEMBER",
  body: "This is an issue against PR #3659,"
  },
  {
  url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3935",
  repository_url: "https://api.github.com/repos/tidyverse/ggplot2",
  labels_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3935/labels{/name}",
  comments_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3935/comments",
  events_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3935/events",
  html_url: "https://github.com/tidyverse/ggplot2/issues/3935",
  id: 596488619,
  node_id: "MDU6SXNzdWU1OTY0ODg2MTk=",
  number: 3935,
  title: "geom_raster ignores color",
  user: {
  login: "bhogan-mitre",
  id: 32336739,
  node_id: "MDQ6VXNlcjMyMzM2NzM5",
  avatar_url: "https://avatars1.githubusercontent.com/u/32336739?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/bhogan-mitre",
  html_url: "https://github.com/bhogan-mitre",
  followers_url: "https://api.github.com/users/bhogan-mitre/followers",
  following_url: "https://api.github.com/users/bhogan-mitre/following{/other_user}",
  gists_url: "https://api.github.com/users/bhogan-mitre/gists{/gist_id}",
  starred_url: "https://api.github.com/users/bhogan-mitre/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/bhogan-mitre/subscriptions",
  organizations_url: "https://api.github.com/users/bhogan-mitre/orgs",
  repos_url: "https://api.github.com/users/bhogan-mitre/repos",
  events_url: "https://api.github.com/users/bhogan-mitre/events{/privacy}",
  received_events_url: "https://api.github.com/users/bhogan-mitre/received_events",
  type: "User",
  site_admin: false
  },
  labels: [
  {
  id: 119475,
  node_id: "MDU6TGFiZWwxMTk0NzU=",
  url: "https://api.github.com/repos/tidyverse/ggplot2/labels/documentation",
  name: "documentation",
  color: "CBBAB8",
  default: true,
  description: ""
  }
  ],
  state: "open",
  locked: false,
  assignee: null,
  assignees: [ ],
  milestone: null,
  comments: 5,
  created_at: "2020-04-08T10:54:27Z",
  updated_at: "2020-04-10T00:14:14Z",
  closed_at: null,
  author_association: "NONE",
  body: "Color is listed as a parameter in the documentation"
  },
  {
  url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3924",
  repository_url: "https://api.github.com/repos/tidyverse/ggplot2",
  labels_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3924/labels{/name}",
  comments_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3924/comments",
  events_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3924/events",
  html_url: "https://github.com/tidyverse/ggplot2/issues/3924",
  id: 593385149,
  node_id: "MDU6SXNzdWU1OTMzODUxNDk=",
  number: 3924,
  title: "Check if the visual tests actually run",
  user: {
  login: "yutannihilation",
  id: 1978793,
  node_id: "MDQ6VXNlcjE5Nzg3OTM=",
  avatar_url: "https://avatars3.githubusercontent.com/u/1978793?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/yutannihilation",
  html_url: "https://github.com/yutannihilation",
  followers_url: "https://api.github.com/users/yutannihilation/followers",
  following_url: "https://api.github.com/users/yutannihilation/following{/other_user}",
  gists_url: "https://api.github.com/users/yutannihilation/gists{/gist_id}",
  starred_url: "https://api.github.com/users/yutannihilation/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/yutannihilation/subscriptions",
  organizations_url: "https://api.github.com/users/yutannihilation/orgs",
  repos_url: "https://api.github.com/users/yutannihilation/repos",
  events_url: "https://api.github.com/users/yutannihilation/events{/privacy}",
  received_events_url: "https://api.github.com/users/yutannihilation/received_events",
  type: "User",
  site_admin: false
  },
  labels: [
  {
  id: 525888326,
  node_id: "MDU6TGFiZWw1MjU4ODgzMjY=",
  url: "https://api.github.com/repos/tidyverse/ggplot2/labels/internals%20:mag_right:",
  name: "internals :mag_right:",
  color: "eeeeee",
  default: false,
  description: ""
  }
  ],
  state: "open",
  locked: false,
  assignee: null,
  assignees: [ ],
  milestone: null,
  comments: 0,
  created_at: "2020-04-03T13:31:48Z",
  updated_at: "2020-04-30T18:48:51Z",
  closed_at: null,
  author_association: "MEMBER",
  body: "(Moved from https://github.com/tidyverse/ggplot2/pull/3922#issuecomment-607288487) Visual tests are so sensitive that it fails even with the subtle changes between R versions that we cannot detect with our eyes. So, it's a common practice to run the tests only on the latest stable version of R. But, sometimes we mistakenly set the CI to skip visual tests on all the versions. Since visual tests are important to detect regressions, we need some way to ensure they actually run. @lionel- says this might require a new feature on vdiffr's (and testthat?) side after R 4.0: > Maybe vdiffr could signal a special condition class when a test is not run. Then a calling (not exiting so other tests keep running) condition handler could transform the condition to an error that would be caught by testthat. > > With R 4.0 it would be easy to do this with a global condition handler, without any change in the ggplot2 sources. On older R we'd need to install the handler around test_check() with withCallingHandlers(), conditionally on some environment variable indicating that the tests should really be run (but then you run into the same issue i.e. is this envvar correctly defined... So the global handler approach is a little more appealing)."
  },
  {
  url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3913",
  repository_url: "https://api.github.com/repos/tidyverse/ggplot2",
  labels_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3913/labels{/name}",
  comments_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3913/comments",
  events_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3913/events",
  html_url: "https://github.com/tidyverse/ggplot2/issues/3913",
  id: 588911320,
  node_id: "MDU6SXNzdWU1ODg5MTEzMjA=",
  number: 3913,
  title: "Export 'binned_scale'",
  user: {
  login: "coolbutuseless",
  id: 181818,
  node_id: "MDQ6VXNlcjE4MTgxOA==",
  avatar_url: "https://avatars0.githubusercontent.com/u/181818?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/coolbutuseless",
  html_url: "https://github.com/coolbutuseless",
  followers_url: "https://api.github.com/users/coolbutuseless/followers",
  following_url: "https://api.github.com/users/coolbutuseless/following{/other_user}",
  gists_url: "https://api.github.com/users/coolbutuseless/gists{/gist_id}",
  starred_url: "https://api.github.com/users/coolbutuseless/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/coolbutuseless/subscriptions",
  organizations_url: "https://api.github.com/users/coolbutuseless/orgs",
  repos_url: "https://api.github.com/users/coolbutuseless/repos",
  events_url: "https://api.github.com/users/coolbutuseless/events{/privacy}",
  received_events_url: "https://api.github.com/users/coolbutuseless/received_events",
  type: "User",
  site_admin: false
  },
  labels: [
  {
  id: 914900944,
  node_id: "MDU6TGFiZWw5MTQ5MDA5NDQ=",
  url: "https://api.github.com/repos/tidyverse/ggplot2/labels/good%20first%20issue%20:heart:",
  name: "good first issue :heart:",
  color: "CBBAB8",
  default: false,
  description: "good issue for first-time contributors"
  },
  {
  id: 526758072,
  node_id: "MDU6TGFiZWw1MjY3NTgwNzI=",
  url: "https://api.github.com/repos/tidyverse/ggplot2/labels/scales%20:snake:",
  name: "scales :snake:",
  color: "eeeeee",
  default: false,
  description: ""
  }
  ],
  state: "open",
  locked: false,
  assignee: null,
  assignees: [ ],
  milestone: {
  url: "https://api.github.com/repos/tidyverse/ggplot2/milestones/21",
  html_url: "https://github.com/tidyverse/ggplot2/milestone/21",
  labels_url: "https://api.github.com/repos/tidyverse/ggplot2/milestones/21/labels",
  id: 5181145,
  node_id: "MDk6TWlsZXN0b25lNTE4MTE0NQ==",
  number: 21,
  title: "ggplot2 3.3.1",
  description: "This will be a small patch release fixing regressions, improving performance, and folding in TDD PRs",
  creator: {
  login: "thomasp85",
  id: 1775316,
  node_id: "MDQ6VXNlcjE3NzUzMTY=",
  avatar_url: "https://avatars3.githubusercontent.com/u/1775316?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/thomasp85",
  html_url: "https://github.com/thomasp85",
  followers_url: "https://api.github.com/users/thomasp85/followers",
  following_url: "https://api.github.com/users/thomasp85/following{/other_user}",
  gists_url: "https://api.github.com/users/thomasp85/gists{/gist_id}",
  starred_url: "https://api.github.com/users/thomasp85/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/thomasp85/subscriptions",
  organizations_url: "https://api.github.com/users/thomasp85/orgs",
  repos_url: "https://api.github.com/users/thomasp85/repos",
  events_url: "https://api.github.com/users/thomasp85/events{/privacy}",
  received_events_url: "https://api.github.com/users/thomasp85/received_events",
  type: "User",
  site_admin: false
  },
  open_issues: 10,
  closed_issues: 34,
  state: "open",
  created_at: "2020-03-09T08:30:16Z",
  updated_at: "2020-05-16T17:04:24Z",
  due_on: null,
  closed_at: null
  },
  comments: 2,
  created_at: "2020-03-27T06:10:41Z",
  updated_at: "2020-05-03T04:42:07Z",
  closed_at: null,
  author_association: "CONTRIBUTOR",
  body: "'discrete_scale' and 'continuous_scale' are both exported. For consistency and ease of extending ggplot2, can 'binned_scale' be exported as well? Tiny PR: https://github.com/tidyverse/ggplot2/pull/3912 "
  },
  {
  url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3912",
  repository_url: "https://api.github.com/repos/tidyverse/ggplot2",
  labels_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3912/labels{/name}",
  comments_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3912/comments",
  events_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3912/events",
  html_url: "https://github.com/tidyverse/ggplot2/pull/3912",
  id: 588910122,
  node_id: "MDExOlB1bGxSZXF1ZXN0Mzk0NTY5NjUw",
  number: 3912,
  title: "export binned_scale",
  user: {
  login: "coolbutuseless",
  id: 181818,
  node_id: "MDQ6VXNlcjE4MTgxOA==",
  avatar_url: "https://avatars0.githubusercontent.com/u/181818?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/coolbutuseless",
  html_url: "https://github.com/coolbutuseless",
  followers_url: "https://api.github.com/users/coolbutuseless/followers",
  following_url: "https://api.github.com/users/coolbutuseless/following{/other_user}",
  gists_url: "https://api.github.com/users/coolbutuseless/gists{/gist_id}",
  starred_url: "https://api.github.com/users/coolbutuseless/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/coolbutuseless/subscriptions",
  organizations_url: "https://api.github.com/users/coolbutuseless/orgs",
  repos_url: "https://api.github.com/users/coolbutuseless/repos",
  events_url: "https://api.github.com/users/coolbutuseless/events{/privacy}",
  received_events_url: "https://api.github.com/users/coolbutuseless/received_events",
  type: "User",
  site_admin: false
  },
  labels: [ ],
  state: "open",
  locked: false,
  assignee: null,
  assignees: [ ],
  milestone: {
  url: "https://api.github.com/repos/tidyverse/ggplot2/milestones/21",
  html_url: "https://github.com/tidyverse/ggplot2/milestone/21",
  labels_url: "https://api.github.com/repos/tidyverse/ggplot2/milestones/21/labels",
  id: 5181145,
  node_id: "MDk6TWlsZXN0b25lNTE4MTE0NQ==",
  number: 21,
  title: "ggplot2 3.3.1",
  description: "This will be a small patch release fixing regressions, improving performance, and folding in TDD PRs",
  creator: {
  login: "thomasp85",
  id: 1775316,
  node_id: "MDQ6VXNlcjE3NzUzMTY=",
  avatar_url: "https://avatars3.githubusercontent.com/u/1775316?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/thomasp85",
  html_url: "https://github.com/thomasp85",
  followers_url: "https://api.github.com/users/thomasp85/followers",
  following_url: "https://api.github.com/users/thomasp85/following{/other_user}",
  gists_url: "https://api.github.com/users/thomasp85/gists{/gist_id}",
  starred_url: "https://api.github.com/users/thomasp85/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/thomasp85/subscriptions",
  organizations_url: "https://api.github.com/users/thomasp85/orgs",
  repos_url: "https://api.github.com/users/thomasp85/repos",
  events_url: "https://api.github.com/users/thomasp85/events{/privacy}",
  received_events_url: "https://api.github.com/users/thomasp85/received_events",
  type: "User",
  site_admin: false
  },
  open_issues: 10,
  closed_issues: 34,
  state: "open",
  created_at: "2020-03-09T08:30:16Z",
  updated_at: "2020-05-16T17:04:24Z",
  due_on: null,
  closed_at: null
  },
  comments: 4,
  created_at: "2020-03-27T06:07:10Z",
  updated_at: "2020-05-15T10:39:44Z",
  closed_at: null,
  author_association: "CONTRIBUTOR",
  pull_request: {
  url: "https://api.github.com/repos/tidyverse/ggplot2/pulls/3912",
  html_url: "https://github.com/tidyverse/ggplot2/pull/3912",
  diff_url: "https://github.com/tidyverse/ggplot2/pull/3912.diff",
  patch_url: "https://github.com/tidyverse/ggplot2/pull/3912.patch"
  },
  body: "'discrete_scale' and 'continuous_scale' are both exported. Can we export 'binned_scale' as well?"
  },
  {
  url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3901",
  repository_url: "https://api.github.com/repos/tidyverse/ggplot2",
  labels_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3901/labels{/name}",
  comments_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3901/comments",
  events_url: "https://api.github.com/repos/tidyverse/ggplot2/issues/3901/events",
  html_url: "https://github.com/tidyverse/ggplot2/issues/3901",
  id: 584841965,
  node_id: "MDU6SXNzdWU1ODQ4NDE5NjU=",
  number: 3901,
  title: "Confusing error message when autogenerated aesthetic is also manually provided",
  user: {
  login: "clauswilke",
  id: 4210929,
  node_id: "MDQ6VXNlcjQyMTA5Mjk=",
  avatar_url: "https://avatars2.githubusercontent.com/u/4210929?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/clauswilke",
  html_url: "https://github.com/clauswilke",
  followers_url: "https://api.github.com/users/clauswilke/followers",
  following_url: "https://api.github.com/users/clauswilke/following{/other_user}",
  gists_url: "https://api.github.com/users/clauswilke/gists{/gist_id}",
  starred_url: "https://api.github.com/users/clauswilke/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/clauswilke/subscriptions",
  organizations_url: "https://api.github.com/users/clauswilke/orgs",
  repos_url: "https://api.github.com/users/clauswilke/repos",
  events_url: "https://api.github.com/users/clauswilke/events{/privacy}",
  received_events_url: "https://api.github.com/users/clauswilke/received_events",
  type: "User",
  site_admin: false
  },
  labels: [
  {
  id: 1802219789,
  node_id: "MDU6TGFiZWwxODAyMjE5Nzg5",
  url: "https://api.github.com/repos/tidyverse/ggplot2/labels/messages",
  name: "messages",
  color: "fef2c0",
  default: false,
  description: "requests for improvements to error, warning, or feedback messages"
  }
  ],
  state: "open",
  locked: false,
  assignee: null,
  assignees: [ ],
  milestone: null,
  comments: 0,
  created_at: "2020-03-20T04:47:04Z",
  updated_at: "2020-04-30T19:00:20Z",
  closed_at: null,
  author_association: "MEMBER",
  body: "This issue was first reported for ggridges (https://github.com/wilkelab/ggridges/issues/56), but it can be reproduced with plain ggplot2. If I set an aesthetic (here `y`) that would normally be calculated by the stat, then the error message is that that aesthetic is missing. This is confusing, because the user has explicitly provided that aesthetic. A better error message would be useful. I haven't investigated yet why this happens. ``` r library(ggplot2) df <- data.frame(x = 1:100, y = (1:100)^2) ggplot(df, aes(x, y)) + geom_density() #> Error: geom_density requires the following missing aesthetics: y ``` <sup>Created on 2020-03-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>"
  }
  ]